services:

  php8site:
    image: annurschule/gibbon:php8.2
    build:
      context: .
    container_name: annur_php_gibbon
    volumes:
      - ..:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - intern-nw-1

  db:
    image: mysql:8
    container_name: gibbon_mysql

    env_file:
      - ../../secrets.env

    environment:
      MYSQL_DATABASE: gibbon_DB
      MYSQL_USER: gibbon
      #Production passwords set in ../../secrets.env

    volumes:
      - /root/schule/gibbon_db:/var/lib/mysql
      - /root/schule/gibbon_db_backup:/var/gibbon_db_backup

    networks:
      - intern-nw-1

    ports:
      - "3306:3306"   # ideally remove this in production

# Network configuration (optional, but recommended for better isolation)
networks:
  intern-nw-1:
    driver: bridge
