services:
  php-8-2-24:
    build:
      context: .
      dockerfile: Dockerfile_test
    image: gibbon_php:8.2.24_test
    container_name: gibbon_php_test
    volumes:
      - C:/Abbadi-local/repo/Annur/core_new_repo:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    container_name: gibbon_mysql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: gibbon
      MYSQL_PASSWORD: gibbon3
      MYSQL_ROOT_PASSWORD: gibbon_roo3
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - C:/Abbadi-local/repo/Annur/DB/test_data:/var/lib/mysql

