# execute the following command
# docker image build -t gibbon_php:8.2.24 . 
#    OR directly use the following command
# docker-compose -f docker-compose.yml up --build

FROM php:8.2.24-apache

RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y libzip-dev zip gettext-base default-mysql-client libpng-dev locales \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libicu-dev
 
RUN docker-php-ext-install zip pdo_mysql gettext gd

RUN docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install -j$(nproc) gd

RUN docker-php-ext-install intl
RUN docker-php-ext-enable intl
RUN locale-gen de_DE.UTF-8
RUN echo "de_DE.UTF-8 UTF-8\nar_SA.UTF-8 UTF-8\nen_GB.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen

#RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
#RUN printf "; Gibbon Parameters\nextension=intl\nexpose_php=Off\nupload_max_filesize = 20M\npost_max_size = 20M\nmemory_limit = 512M\nmax_input_vars=5000\nregister_globals = off\nmax_file_uploads=30\nerror_reporting = E_ALL & ~E_NOTICE\nallow_url_fopen=On" >> "$PHP_INI_DIR/php.ini"

##debug 

# ToDebug commit the above PHP_INI line
# ToDebug uncommited the following lines

RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN printf "; Gibbon Parameters\nextension=intl\nexpose_php=Off\nupload_max_filesize = 20M\npost_max_size = 20M\nmemory_limit = 512M\nmax_input_vars=5000\nregister_globals = off\nmax_file_uploads=30\nerror_reporting = E_ALL & ~E_NOTICE\nallow_url_fopen=On \n[xdebug] \nxdebug.mode = debug\nxdebug.start_with_request = yes\nxdebug.client_host = host.docker.internal" >> "$PHP_INI_DIR/php.ini"

## END debug dependancy

RUN chmod -Rv 755 /var/www/html/ 

COPY ./apache/000-default.conf /etc/apache2/sites-available/000-default.conf


# Configure Xdebug (adjust settings as needed)
RUN echo "zend_extension=xdebug.so" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_port=9003" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.idekey=VSCODE" >> /usr/local/etc/php/conf.d/xdebug.ini



RUN a2enmod ssl && a2enmod rewrite
RUN echo 'root:Root!1&%^' | chpasswd

EXPOSE 80
EXPOSE 3306
EXPOSE 9003

